### ISSUE TITLE
What is the reason for the following error when I test times

### ISSUE THREAD

**Issue by zlf123-marker** [uci-cbcl/DeepLung#17]
results/res18/retrft969/bbox
(18, 1, 208, 208, 208)
main.py:327: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input = Variable(data[splitlist[i]:splitlist[i+1]], volatile = True).cuda()
main.py:328: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputcoord = Variable(coord[splitlist[i]:splitlist[i+1]], volatile = True).cuda()
Traceback (most recent call last):
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/multiprocessing/queue.py", line 18, in send
    self.send_bytes(buf.getvalue())
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "main.py", line 387, in <module>
    main()
  File "main.py", line 148, in main
    test(test_loader, net, get_pbb, save_dir,config)
  File "main.py", line 333, in test
    output = net(input,inputcoord)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zlf/DeepLung/detector/res18.py", line 97, in forward
    out = self.preBlock(x)#16
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 476, in forward
    self.padding, self.dilation, self.groups)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 23743) is killed by signal: Killed.

**Comment by wentaozhu** [comment]
Try to use this repository https://github.com/wentaozhu/DeepLung/blob/master/detector/main.py
Try to set -j as 0.

**Comment by zlf123-marker** [comment]
results/res18/retrft969/bbox
(18, 1, 208, 208, 208)
main.py:327: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  input = Variable(data[splitlist[i]:splitlist[i+1]], volatile = True).cuda()
main.py:328: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  inputcoord = Variable(coord[splitlist[i]:splitlist[i+1]], volatile = True).cuda()
Traceback (most recent call last):
  File "main.py", line 387, in <module>
    main()
  File "main.py", line 148, in main
    test(test_loader, net, get_pbb, save_dir,config)
  File "main.py", line 333, in test
    output = net(input,inputcoord)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zlf/DeepLung/detector/res18.py", line 97, in forward
    out = self.preBlock(x)#16
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zlf/anaconda3/envs/deeplung/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 476, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 156.00 MiB (GPU 0; 10.73 GiB total capacity; 9.82 GiB already allocated; 75.44 MiB free; 4.94 MiB cached)

**Comment by zlf123-marker** [comment]
What is the reason for the following error when I test times

**Comment by wentaozhu** [comment]
GPU out of memory. Please check https://github.com/wentaozhu/DeepLung/blob/master/detector/main.py for related issues.
